disallowed-types = [
    { path = "axum::extract::query::Query", reason = "此 crate 禁止使用 axum::extract::query", replacement = "starriver_base::extract::Query" },
    { path = "axum::extract::path::Path", reason = "此 crate 禁止使用 axum::extract::path", replacement = "starriver_base::extract::Path" },
    { path = "axum::Json", reason = "此 crate 禁止使用 axum::Json", replacement = "starriver_base::extract::Json/JsonEx" },
    { path = "axum::extract::multipart::Multipart", reason = "此 crate 禁止使用 axum::extract::multipart", replacement = "starriver_base::extract::Multipart" },
]

disallowed-methods = [
    { path = "uuid::Uuid::new_v4", reason = "避免使用v4", replacement = "uuid::Uuid::now_v7" },
]
