[package]
name = "starriver-blogging-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
starriver-blogging-domain = {path = "../domain"}
starriver-shared-base = { workspace = true }

moka = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
